[feat/main_search] 메인페이지에서 검색 기능 작동시키기(#133)
hyewon-han/baple pull request #134
Opened 2024-01-27 08:23 UTC by Laejun-Kim

* 메인 페이지 검색 기능 places 페이지와 연결
 * 메인 페이지에서 검색하면 자동으로 해당 검색어와 검색 결과를 가지고 places 페이지로 넘어감
 
!! 검색 필터를 설정하는 '순서' 에 따라서 검색 결과가 다르게 나타나는 기괴한 문제 발견.
해당 문제가 새로 발생한 것일 경우 merge 유보. 기존에 존재하던 문제라면 merge. 

![스크린샷 2024-01-27 171433](https://github.com/hyewon-han/baple/assets/49670820/fac04ae3-5a1c-499a-aeee-e64043f0fec0)
![스크린샷 2024-01-27 171441](https://github.com/hyewon-han/baple/assets/49670820/7fa1ca59-1684-4a97-9a43-e438ad456520)

[장애인용 출입문 -> 휠체어 대여 ] 순서로 눌렀을 경우
![스크린샷 2024-01-27 172116](https://github.com/hyewon-han/baple/assets/49670820/ea331d93-6d05-40e6-8b3c-c24e46375cc0)

[휠체어 대여 -> 장애인용 출입문 ] 순서로 눌렀을 경우
![스크린샷 2024-01-27 172124](https://github.com/hyewon-han/baple/assets/49670820/8a9fb32a-d24a-4e36-8ffa-aa42e8c9395c)

2024-01-27 09:57 UTC, hyewon-han approved these changes
최고입니다...!!👍

2024-01-27 12:57 UTC, hyewon-han requested changes

2024-01-27 12:57 UTC, hyewon-han commented on src/pages/index.tsx
useRouter 임포트 해오는 부분에서 (16번쨰 라인) next/navigation 은 앱 라우터에서 사용하는 useRouter. 입니다! next/router 에서 import 해주세요!

2024-01-28 02:14 UTC, Laejun-Kim commented on src/pages/index.tsx
수정했습니다 감사합니다 :)

2024-01-28 05:11 UTC, hyewon-han approved these changes
최고입니다..!!!!!!!

2024-01-28 05:11 UTC, mi-hee-k approved these changes
LGTM

2024-01-28 05:12 UTC, merged